// src/context/LanguageContext.tsx
'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'hi' | 'hinglish';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('preferredLanguage') as Language;
    if (saved && ['en', 'hi', 'hinglish'].includes(saved)) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('preferredLanguage', lang);
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      if (value && typeof value === 'object') {
        value = value[k];
      } else {
        return key;
      }
    }
    
    return typeof value === 'string' ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

const translations = {
  en: {
    common: {
      dashboard: 'Dashboard',
      logout: 'Logout',
      loading: 'Loading...',
      save: 'Save',
      cancel: 'Cancel',
      submit: 'Submit',
      back: 'Back',
      next: 'Next',
      delete: 'Delete',
      edit: 'Edit',
      add: 'Add',
      search: 'Search',
      filter: 'Filter',
    },
    nav: {
      dashboard: 'Dashboard',
      liveTracking: 'Live Tracking',
      dispatchTransport: 'Dispatch & Transport',
      bookManagement: 'Book Management',
      approvals: 'Approvals',
      orders: 'Orders',
      reports: 'Reports',
      teamManagement: 'Team Management',
      myTeam: 'My Team',
      myDay: 'My Day',
      routePlan: 'Route Plan',
      myStock: 'My Stock',
      myExpenses: 'My Expenses',
      myOrders: 'My Orders',
    },
    visit: {
      title: 'Visit Execution',
      checkInTitle: 'Step 1: Proof of Visit',
      checkInDesc: 'To begin, please take a photo of the school entrance.',
      takePhoto: 'Take Photo to Check-in',
      processing: 'Processing...',
      principalMeeting: 'Step 2: Principal Meeting',
      principalName: 'Principal Name',
      studentCount: 'Total Student Count',
      remarks: 'Meeting Remarks',
      remarksPlaceholder: 'Type notes here...',
      teacherInfo: 'Teacher Information (from Principal)',
      teacherName: 'Teacher Name',
      selectSubject: 'Select Subject',
      selectClass: 'Select Class',
      addTeacher: 'Add Teacher to List',
      permission: 'Permission granted to meet teachers?',
      saveAndProceed: 'Save & Proceed to Teacher Meeting',
      saveAndComplete: 'Save & Complete Visit',
      backToMyDay: 'Back to My Day',
      congratulations: 'Congratulations!',
      targetCompleted: 'You have completed your Daily Allowance target for today.',
      checkInFailed: 'Check-in Failed',
      tryAgain: 'Please try again.',
      locationError: 'Could not get location. Please enable location services.',
      fillAllDetails: 'Please fill all teacher details.',
    },
    exec: {
  hello: 'Hello',
  startDay: 'Start Day',
  endDay: 'End Day',
  todaysRoute: 'Today\'s Route',
  planNewVisit: 'Plan New Visit',
  todaysVisits: 'Today\'s Visits',
  refresh: 'Refresh Plan',
  noVisits: 'No visits planned for today',
  completed: 'Completed',
  readyToStart: 'Ready to start',
  pendingSync: 'Plan is pending sync',
  start: 'Start',
  pendingConsignments: 'Pending Consignments',
  bilty: 'Bilty',
  view: 'View',
  // ... existing translations
  errorTitle: 'Error',
  dayStartedTitle: 'Day Started!',
  dayStartedDesc: 'Your workday has started successfully',
  startDayError: 'Could not start day. Please try again.',
  dayEndedTitle: 'Day Ended!',
  dayEndedDesc: 'Your workday ended. Expenses have been generated.',
  endDayError: 'Could not end day. Please try again.',

},
route: {
  loading: 'Loading your route plan...',
  title: 'Today\'s Optimized Route Plan',
  summary: 'Route Summary',
  totalDistance: 'Total Distance',
  travelTime: 'Est. Travel Time',
  itinerary: 'Your Itinerary',
  navigate: 'Navigate',
  startVisit: 'Start Visit',
  estimatedTravel: 'Est. travel',
  yourLocation: 'Your Location',
},
stockPage: {
  title: 'My Stock',
  items: 'Items',
  quickSummary: 'Quick Summary',
  stock: 'Stock',
  assigned: 'Assigned',
  distributed: 'Distributed',
  searchPlaceholder: 'Search books...',
  noBooksFound: 'No books found',
  tryDifferent: 'Try different search terms',
  noInventory: 'No inventory assigned',
  consignmentsWillAppear: 'Consignments will appear here',
},expensePage: {
  loading: 'Loading your expenses...',
  title: 'My Expenses',
  addNew: 'Add New Expense',
  history: 'Expense History',
  dailyAllowance: 'Daily Allowance',
  travelAllowance: 'Travel Allowance',
  otherExpense: 'Other Expense',
  approved: 'Approved',
  rejected: 'Rejected',
  pending: 'Pending',
  noExpenses: 'You have no expenses logged.',
},ordersPage: {
  loading: 'Loading your generated orders...',
  title: 'My Generated Orders',
  history: 'Order History',
  totalOrders: 'Total Orders',
  noOrders: 'You have not generated any orders yet.',
  orderDate: 'Order Date',
  location: 'Location',
  teacher: 'Teacher',
  bookDetails: 'Book Details',
  quantity: 'Quantity',
  class: 'Class',
  subject: 'Subject',
},planMap: {
  searchPlaceholder: 'Search existing locations or find new ones on Google...',
  ourDatabase: 'Our Database',
  googleSuggestions: 'Google Maps Suggestions',
  locationsSelected: 'Location(s) Selected',
  schools: 'Schools',
  coaching: 'Coaching',
  shops: 'Shops',
  adding: 'Adding to Plan...',
  addVisits: 'Add {count} Visits to Plan',
  error: 'Error',
  selectDateAndLocation: 'Please select a date and at least one location.',
  success: 'Success!',
  planCreated: 'Plan created successfully!',
  planError: 'An error occurred while creating the plan.',
},
orderModal: {
  title: 'Place New Order',
  class: 'Class',
  subject: 'Subject',
  book: 'Book',
  selectBook: 'Select a book',
  quantity: 'Quantity',
  orderItems: 'Order Items',
  qty: 'Qty',
  noItemsAdded: 'No items added yet',
  noBooksAvailable: 'No books available for this teacher',
  success: 'Success!',
  orderPlaced: 'Order placed successfully!',
  error: 'Error',
  orderFailed: 'Failed to place order',
  noItems: 'No Items',
  addItemsFirst: 'Please add items to the order first',
  placeOrder: 'Place Order',
},

giveBookModal: {
  title: 'Give Book to Teacher',
  class: 'Class',
  subject: 'Subject',
  book: 'Book',
  selectBook: 'Select a book to give',
  quantity: 'Quantity',
  inStock: 'in stock',
  available: 'available',
  noBooksAvailable: 'No books available for this teacher',
  error: 'Error',
  selectBookFirst: 'Please select a book first',
  notEnoughStock: 'Not enough stock available',
  success: 'Success!',
  bookAdded: 'Book added to distribution list',
  addToList: 'Add to List',
},
    auth: {
      loadingSession: 'Loading Session...',
    },
  },
  hi: {
    common: {
      dashboard: 'डैशबोर्ड',
      logout: 'लॉगआउट',
      loading: 'लोड हो रहा है...',
      save: 'सहेजें',
      cancel: 'रद्द करें',
      submit: 'जमा करें',
      back: 'पीछे',
      next: 'आगे',
      delete: 'हटाएं',
      edit: 'संपादित करें',
      add: 'जोड़ें',
      search: 'खोजें',
      filter: 'फ़िल्टर',
    },
    nav: {
      dashboard: 'डैशबोर्ड',
      liveTracking: 'लाइव ट्रैकिंग',
      dispatchTransport: 'प्रेषण और परिवहन',
      bookManagement: 'पुस्तक प्रबंधन',
      approvals: 'स्वीकृतियां',
      orders: 'आदेश',
      reports: 'रिपोर्ट',
      teamManagement: 'टीम प्रबंधन',
      myTeam: 'मेरी टीम',
      myDay: 'मेरा दिन',
      routePlan: 'मार्ग योजना',
      myStock: 'मेरा स्टॉक',
      myExpenses: 'मेरे खर्च',
      myOrders: 'मेरे आदेश',
    },
    visit: {
      title: 'विज़िट निष्पादन',
      checkInTitle: 'चरण 1: विज़िट का प्रमाण',
      checkInDesc: 'शुरू करने के लिए, कृपया स्कूल के प्रवेश द्वार की तस्वीर लें।',
      takePhoto: 'चेक-इन के लिए फोटो लें',
      processing: 'प्रक्रिया चल रही है...',
      principalMeeting: 'चरण 2: प्रधानाचार्य बैठक',
      principalName: 'प्रधानाचार्य का नाम',
      studentCount: 'कुल छात्र संख्या',
      remarks: 'बैठक टिप्पणियां',
      remarksPlaceholder: 'यहां नोट्स टाइप करें...',
      teacherInfo: 'शिक्षक जानकारी (प्रधानाचार्य से)',
      teacherName: 'शिक्षक का नाम',
      selectSubject: 'विषय चुनें',
      selectClass: 'कक्षा चुनें',
      addTeacher: 'शिक्षक को सूची में जोड़ें',
      permission: 'शिक्षकों से मिलने की अनुमति दी गई?',
      saveAndProceed: 'सहेजें और शिक्षक बैठक के लिए आगे बढ़ें',
      saveAndComplete: 'सहेजें और विज़िट पूर्ण करें',
      backToMyDay: 'मेरे दिन पर वापस जाएं',
      congratulations: 'बधाई हो!',
      targetCompleted: 'आपने आज के लिए अपना दैनिक भत्ता लक्ष्य पूरा कर लिया है।',
      checkInFailed: 'चेक-इन विफल',
      tryAgain: 'कृपया पुनः प्रयास करें।',
      locationError: 'स्थान नहीं मिल सका। कृपया स्थान सेवाएं सक्षम करें।',
      fillAllDetails: 'कृपया शिक्षक के सभी विवरण भरें।',
    },
    exec: {
  hello: 'नमस्ते',
  startDay: 'दिन शुरू करें',
  endDay: 'दिन समाप्त करें',
  todaysRoute: 'आज का मार्ग',
  planNewVisit: 'नई विज़िट योजना',
  todaysVisits: 'आज की विज़िट',
  refresh: 'रीफ़्रेश करें',
  noVisits: 'आज के लिए कोई विज़िट नहीं',
  completed: 'पूर्ण',
  readyToStart: 'शुरू करने के लिए तैयार',
  pendingSync: 'योजना सिंक में है',
  start: 'शुरू करें',
  pendingConsignments: 'लंबित माल',
  bilty: 'बिल्टी',
  view: 'देखें',
  // ... existing translations
  errorTitle: 'त्रुटि',
  dayStartedTitle: 'दिन शुरू हुआ!',
  dayStartedDesc: 'आपका कार्य दिवस सफलतापूर्वक शुरू हो गया',
  startDayError: 'दिन शुरू नहीं हो सका। कृपया पुनः प्रयास करें।',
  dayEndedTitle: 'दिन समाप्त हुआ!',
  dayEndedDesc: 'आपका कार्य दिवस समाप्त हुआ। खर्च बन गए हैं।',
  endDayError: 'दिन समाप्त नहीं हो सका। कृपया पुनः प्रयास करें।',
},
route: {
  loading: 'आपकी मार्ग योजना लोड हो रही है...',
  title: 'आज की अनुकूलित मार्ग योजना',
  summary: 'मार्ग सारांश',
  totalDistance: 'कुल दूरी',
  travelTime: 'अनुमानित यात्रा समय',
  itinerary: 'आपका कार्यक्रम',
  navigate: 'नेविगेट करें',
  startVisit: 'विज़िट शुरू करें',
  estimatedTravel: 'अनुमानित यात्रा',
  yourLocation: 'आपका स्थान',
},
stockPage: {
  title: 'मेरा स्टॉक',
  items: 'वस्तुएं',
  quickSummary: 'त्वरित सारांश',
  stock: 'स्टॉक',
  assigned: 'सौंपा गया',
  distributed: 'वितरित',
  searchPlaceholder: 'पुस्तकें खोजें...',
  noBooksFound: 'कोई पुस्तक नहीं मिली',
  tryDifferent: 'अलग खोज शब्द आज़माएं',
  noInventory: 'कोई स्टॉक नहीं',
  consignmentsWillAppear: 'माल यहां दिखाई देगा',
},
expensePage: {
  loading: 'आपके खर्च लोड हो रहे हैं...',
  title: 'मेरे खर्च',
  addNew: 'नया खर्च जोड़ें',
  history: 'खर्च इतिहास',
  dailyAllowance: 'दैनिक भत्ता',
  travelAllowance: 'यात्रा भत्ता',
  otherExpense: 'अन्य खर्च',
  approved: 'स्वीकृत',
  rejected: 'अस्वीकृत',
  pending: 'लंबित',
  noExpenses: 'आपका कोई खर्च दर्ज नहीं है।',
},ordersPage: {
  loading: 'आपके आदेश लोड हो रहे हैं...',
  title: 'मेरे बनाए गए आदेश',
  history: 'आदेश इतिहास',
  totalOrders: 'कुल आदेश',
  noOrders: 'आपने अभी तक कोई आदेश नहीं बनाया है।',
  orderDate: 'आदेश की तारीख',
  location: 'स्थान',
  teacher: 'शिक्षक',
  bookDetails: 'पुस्तक विवरण',
  quantity: 'मात्रा',
  class: 'कक्षा',
  subject: 'विषय',
},planMap: {
  searchPlaceholder: 'मौजूदा स्थान खोजें या Google पर नए खोजें...',
  ourDatabase: 'हमारा डेटाबेस',
  googleSuggestions: 'Google Maps सुझाव',
  locationsSelected: 'स्थान चयनित',
  schools: 'स्कूल',
  coaching: 'कोचिंग',
  shops: 'दुकानें',
  adding: 'योजना में जोड़ा जा रहा है...',
  addVisits: '{count} विज़िट योजना में जोड़ें',
  error: 'त्रुटि',
  selectDateAndLocation: 'कृपया एक तारीख और कम से कम एक स्थान चुनें।',
  success: 'सफलता!',
  planCreated: 'योजना सफलतापूर्वक बनाई गई!',
  planError: 'योजना बनाते समय त्रुटि हुई।',
},teacherPage: {
  title: 'शिक्षक बातचीत',
  findTeacher: 'शिक्षक खोजें या जोड़ें',
  selectTeacher: 'बातचीत करने के लिए शिक्षक चुनें',
  meetingWith: 'बैठक',
  whatsappNumber: 'शिक्षक का व्हाट्सएप नंबर',
  booksDistributed: 'वितरित पुस्तकें',
  qty: 'मात्रा',
  giveBook: 'पुस्तक दें',
  recommendBooks: 'क्या शिक्षक ने पुस्तकों की सिफारिश की?',
  placeOrder: 'क्या शिक्षक ने आदेश दिया?',
  completeMeeting: 'बैठक पूर्ण करें',
  endVisit: 'स्कूल विज़िट समाप्त करें और डैशबोर्ड पर जाएं',
  error: 'त्रुटि',
  fetchError: 'डेटा लाने में विफल',
  savingError: 'बैठक विवरण सहेजने में त्रुटि',
  meetingComplete: 'बैठक पूर्ण',
  completed: 'सफलतापूर्वक पूर्ण हुई',
  confirmEnd: 'क्या आप वाकई इस स्कूल विज़िट को समाप्त करना चाहते हैं?',
  visitEnded: 'विज़िट समाप्त',
  visitEndedDesc: 'स्कूल विज़िट पूर्ण चिह्नित की गई',
  endVisitError: 'विज़िट समाप्त करने में त्रुटि। कृपया पुनः प्रयास करें।',
},

orderModal: {
  title: 'नया आदेश दें',
  class: 'कक्षा',
  subject: 'विषय',
  book: 'पुस्तक',
  selectBook: 'पुस्तक चुनें',
  quantity: 'मात्रा',
  orderItems: 'आदेश वस्तुएं',
  qty: 'मात्रा',
  noItemsAdded: 'अभी तक कोई वस्तु नहीं जोड़ी गई',
  noBooksAvailable: 'इस शिक्षक के लिए कोई पुस्तक उपलब्ध नहीं',
  success: 'सफलता!',
  orderPlaced: 'आदेश सफलतापूर्वक दिया गया!',
  error: 'त्रुटि',
  orderFailed: 'आदेश देने में विफल',
  noItems: 'कोई वस्तु नहीं',
  addItemsFirst: 'कृपया पहले आदेश में वस्तुएं जोड़ें',
  placeOrder: 'आदेश दें',
},

giveBookModal: {
  title: 'शिक्षक को पुस्तक दें',
  class: 'कक्षा',
  subject: 'विषय',
  book: 'पुस्तक',
  selectBook: 'देने के लिए पुस्तक चुनें',
  quantity: 'मात्रा',
  inStock: 'स्टॉक में',
  available: 'उपलब्ध',
  noBooksAvailable: 'इस शिक्षक के लिए कोई पुस्तक उपलब्ध नहीं',
  error: 'त्रुटि',
  selectBookFirst: 'कृपया पहले एक पुस्तक चुनें',
  notEnoughStock: 'पर्याप्त स्टॉक उपलब्ध नहीं',
  success: 'सफलता!',
  bookAdded: 'पुस्तक वितरण सूची में जोड़ी गई',
  addToList: 'सूची में जोड़ें',
},
    auth: {
      loadingSession: 'सत्र लोड हो रहा है...',
    },
  },
  hinglish: {
    common: {
      dashboard: 'Dashboard',
      logout: 'Logout',
      loading: 'Load ho raha hai...',
      save: 'Save karein',
      cancel: 'Cancel karein',
      submit: 'Submit karein',
      back: 'Peeche',
      next: 'Aage',
      delete: 'Delete karein',
      edit: 'Edit karein',
      add: 'Add karein',
      search: 'Search karein',
      filter: 'Filter karein',
    },
    nav: {
      dashboard: 'Dashboard',
      liveTracking: 'Live Tracking',
      dispatchTransport: 'Dispatch & Transport',
      bookManagement: 'Book Management',
      approvals: 'Approvals',
      orders: 'Orders',
      reports: 'Reports',
      teamManagement: 'Team Management',
      myTeam: 'Meri Team',
      myDay: 'Mera Din',
      routePlan: 'Route Plan',
      myStock: 'Mera Stock',
      myExpenses: 'Mere Expenses',
      myOrders: 'Mere Orders',
    },
    visit: {
      title: 'Visit Execution',
      checkInTitle: 'Step 1: Visit ka Proof',
      checkInDesc: 'Shuru karne ke liye, school ke entrance ki photo lijiye.',
      takePhoto: 'Check-in ke liye Photo lijiye',
      processing: 'Process ho raha hai...',
      principalMeeting: 'Step 2: Principal Meeting',
      principalName: 'Principal ka Naam',
      studentCount: 'Total Student Count',
      remarks: 'Meeting Remarks',
      remarksPlaceholder: 'Yahan notes type karein...',
      teacherInfo: 'Teacher Information (Principal se)',
      teacherName: 'Teacher ka Naam',
      selectSubject: 'Subject Select karein',
      selectClass: 'Class Select karein',
      addTeacher: 'Teacher ko List mein Add karein',
      permission: 'Teachers se milne ki permission mili?',
      saveAndProceed: 'Save karein aur Teacher Meeting ke liye proceed karein',
      saveAndComplete: 'Save karein aur Visit complete karein',
      backToMyDay: 'Mere Din par wapas jaayein',
      congratulations: 'Badhai ho!',
      targetCompleted: 'Aapne aaj ka apna Daily Allowance target complete kar liya hai.',
      checkInFailed: 'Check-in Failed',
      tryAgain: 'Please phir se try karein.',
      locationError: 'Location nahi mil saki. Please location services enable karein.',
      fillAllDetails: 'Please teacher ke saare details bharein.',
    },exec: {
  hello: 'Hello',
  startDay: 'Din Shuru Karein',
  endDay: 'Din Khatam Karein',
  todaysRoute: 'Aaj ka Route',
  planNewVisit: 'Nayi Visit Plan Karein',
  todaysVisits: 'Aaj ki Visits',
  refresh: 'Refresh Karein',
  noVisits: 'Aaj koi visit nahi hai',
  completed: 'Complete',
  readyToStart: 'Shuru karne ke liye ready',
  pendingSync: 'Plan sync ho raha hai',
  start: 'Shuru Karein',
  pendingConsignments: 'Pending Consignments',
  bilty: 'Bilty',
  view: 'Dekhein',
  // ... existing translations
  errorTitle: 'Error',
  dayStartedTitle: 'Din Shuru Hua!',
  dayStartedDesc: 'Aapka workday successfully shuru ho gaya',
  startDayError: 'Din shuru nahi ho saka. Please phir se try karein.',
  dayEndedTitle: 'Din Khatam Hua!',
  dayEndedDesc: 'Aapka workday khatam hua. Expenses generate ho gaye.',
  endDayError: 'Din khatam nahi ho saka. Please phir se try karein.',

},
route: {
  loading: 'Aapki route plan load ho rahi hai...',
  title: 'Aaj ki Optimized Route Plan',
  summary: 'Route Summary',
  totalDistance: 'Total Distance',
  travelTime: 'Estimated Travel Time',
  itinerary: 'Aapka Itinerary',
  navigate: 'Navigate Karein',
  startVisit: 'Visit Shuru Karein',
  estimatedTravel: 'Estimated travel',
  yourLocation: 'Aapka Location',
},
stockPage: {
  title: 'Mera Stock',
  items: 'Items',
  quickSummary: 'Quick Summary',
  stock: 'Stock',
  assigned: 'Assigned',
  distributed: 'Distributed',
  searchPlaceholder: 'Books search karein...',
  noBooksFound: 'Koi book nahi mili',
  tryDifferent: 'Alag search words try karein',
  noInventory: 'Koi inventory assign nahi hui',
  consignmentsWillAppear: 'Consignments yahan dikhenge',
},
expensePage: {
  loading: 'Aapke expenses load ho rahe hain...',
  title: 'Mere Expenses',
  addNew: 'Naya Expense Add Karein',
  history: 'Expense History',
  dailyAllowance: 'Daily Allowance',
  travelAllowance: 'Travel Allowance',
  otherExpense: 'Other Expense',
  approved: 'Approved',
  rejected: 'Rejected',
  pending: 'Pending',
  noExpenses: 'Aapka koi expense log nahi hai.',
},ordersPage: {
  loading: 'Aapke orders load ho rahe hain...',
  title: 'Mere Generated Orders',
  history: 'Order History',
  totalOrders: 'Total Orders',
  noOrders: 'Aapne abhi tak koi order nahi banaya hai.',
  orderDate: 'Order Date',
  location: 'Location',
  teacher: 'Teacher',
  bookDetails: 'Book Details',
  quantity: 'Quantity',
  class: 'Class',
  subject: 'Subject',
},planMap: {
  searchPlaceholder: 'Existing locations search karein ya Google pe naye dhundhe...',
  ourDatabase: 'Hamara Database',
  googleSuggestions: 'Google Maps Suggestions',
  locationsSelected: 'Locations Selected',
  schools: 'Schools',
  coaching: 'Coaching',
  shops: 'Shops',
  adding: 'Plan mein add ho raha hai...',
  addVisits: '{count} Visits Plan mein Add karein',
  error: 'Error',
  selectDateAndLocation: 'Please ek date aur kam se kam ek location select karein.',
  success: 'Success!',
  planCreated: 'Plan successfully bana diya gaya!',
  planError: 'Plan banate waqt error aayi.',
},teacherPage: {
  title: 'Teacher Interactions',
  findTeacher: 'Teacher Dhundhe ya Add Karein',
  selectTeacher: 'Interact karne ke liye teacher select karein',
  meetingWith: 'Meeting with',
  whatsappNumber: 'Teacher ka WhatsApp Number',
  booksDistributed: 'Books Distributed',
  qty: 'Qty',
  giveBook: 'Book Dein',
  recommendBooks: 'Kya teacher ne books recommend ki?',
  placeOrder: 'Kya teacher ne order diya?',
  completeMeeting: 'Meeting Complete Karein',
  endVisit: 'School Visit End Karein aur Dashboard pe Jaayein',
  error: 'Error',
  fetchError: 'Data fetch karne mein fail',
  savingError: 'Meeting details save karne mein error',
  meetingComplete: 'Meeting Complete',
  completed: 'successfully complete hui',
  confirmEnd: 'Kya aap sure hain ki aap is school visit ko end karna chahte hain?',
  visitEnded: 'Visit End Hui',
  visitEndedDesc: 'School visit complete mark ho gayi',
  endVisitError: 'Visit end karne mein error. Please phir se try karein.',
},

orderModal: {
  title: 'Naya Order Dein',
  class: 'Class',
  subject: 'Subject',
  book: 'Book',
  selectBook: 'Book select karein',
  quantity: 'Quantity',
  orderItems: 'Order Items',
  qty: 'Qty',
  noItemsAdded: 'Abhi tak koi item add nahi hui',
  noBooksAvailable: 'Is teacher ke liye koi book available nahi',
  success: 'Success!',
  orderPlaced: 'Order successfully place ho gaya!',
  error: 'Error',
  orderFailed: 'Order place karne mein fail',
  noItems: 'Koi Items Nahi',
  addItemsFirst: 'Please pehle order mein items add karein',
  placeOrder: 'Order Place Karein',
},

giveBookModal: {
  title: 'Teacher ko Book Dein',
  class: 'Class',
  subject: 'Subject',
  book: 'Book',
  selectBook: 'Dene ke liye book select karein',
  quantity: 'Quantity',
  inStock: 'stock mein',
  available: 'available',
  noBooksAvailable: 'Is teacher ke liye koi book available nahi',
  error: 'Error',
  selectBookFirst: 'Please pehle ek book select karein',
  notEnoughStock: 'Sufficient stock available nahi',
  success: 'Success!',
  bookAdded: 'Book distribution list mein add ho gayi',
  addToList: 'List mein Add Karein',
},
    auth: {
      loadingSession: 'Session load ho raha hai...',
    },
  },
};